from pathlib import Path

path = Path('/home/ubuntu/cummins-sipatma-challenge/client/src/App.tsx')
text = path.read_text()
anchor = 'const sectorOptions = ['
insert_at = text.index(anchor)
questions = r'''  question(17, "Segurança", "safety", "Fácil", "Por que uma área isolada deve ser respeitada?", ["Porque o isolamento indica um risco que precisa ser controlado", "Porque evita conversa", "Porque é uma regra apenas para visitantes", "Porque aumenta a velocidade"], 0, "Respeitar isolamentos evita que pessoas entrem em áreas com energia, movimentação ou condições perigosas."),
  question(18, "Segurança", "safety", "Fácil", "Ao ouvir um alarme de emergência, qual é a primeira atitude?", ["Continuar trabalhando até alguém explicar", "Pegar o celular para filmar", "Interromper com segurança e seguir a rota e orientação previstas", "Correr para a área mais próxima"], 2, "Alarmes devem ser tratados com seriedade: pare com segurança e siga o plano de emergência."),
  question(19, "Segurança", "safety", "Fácil", "Uma ferramenta danificada deve ser:", ["Usada com mais cuidado", "Retirada de uso, identificada e comunicada", "Compartilhada com outra equipe", "Guardada sem avisar"], 1, "Ferramentas danificadas podem falhar e causar lesões; retire-as de uso e comunique o desvio."),
  question(20, "Segurança", "safety", "Fácil", "Qual atitude ajuda a manter uma rota de fuga segura?", ["Deixar materiais temporariamente no corredor", "Usar a rota como área de descanso", "Guardar caixas perto da porta", "Manter passagem, portas e sinalização livres"], 3, "Rotas de fuga precisam permanecer acessíveis, visíveis e livres de obstáculos."),
  question(21, "Segurança", "safety", "Médio", "Antes de intervir em uma máquina, a equipe deve confirmar:", ["Apenas se a máquina está desligada no painel", "O isolamento das fontes de energia e a ausência de energia residual", "Se há outra pessoa olhando", "Se a produção está atrasada"], 1, "O controle de energias perigosas exige isolamento, bloqueio, identificação e verificação."),
  question(22, "Segurança", "safety", "Médio", "Qual exemplo representa uma condição insegura?", ["Piso molhado sem sinalização em uma área de circulação", "Checklist preenchido antes da tarefa", "Ferramenta guardada no local definido", "Proteção instalada e inspecionada"], 0, "Condições inseguras devem ser identificadas, sinalizadas e corrigidas antes de causar um acidente."),
  question(23, "Segurança", "safety", "Médio", "Se o procedimento não contempla uma situação encontrada, o mais seguro é:", ["Improvisar seguindo a experiência", "Copiar o que outra pessoa fez", "Parar, avaliar o risco e buscar orientação responsável", "Continuar para não perder a meta"], 2, "Quando há dúvida ou mudança de condição, pare e busque orientação; improviso aumenta a exposição ao risco."),
  question(24, "Segurança", "safety", "Médio", "Ao levantar uma carga manualmente, você deve primeiro:", ["Testar o peso, avaliar a rota e usar ajuda ou recurso adequado", "Puxar rapidamente", "Girar o tronco para mudar de direção", "Levantar sozinho para demonstrar força"], 0, "Avaliar peso, pega, rota e necessidade de auxílio reduz sobrecarga e lesões musculoesqueléticas."),
  question(25, "Segurança", "safety", "Médio", "O que uma conversa de segurança eficaz deve fazer?", ["Culpar quem errou", "Ser rápida e sem perguntas", "Focar somente na meta", "Abrir espaço para riscos, dúvidas e controles"], 3, "Uma boa conversa permite que as pessoas relatem riscos e confirmem como trabalhar de forma segura."),
  question(26, "Segurança", "safety", "Médio", "Durante uma movimentação com empilhadeira, pedestres devem:", ["Passar atrás do equipamento se houver espaço", "Manter distância, respeitar rotas e contato visual quando necessário", "Correr para atravessar antes", "Ficar atrás da carga para se proteger"], 1, "Equipamentos móveis exigem segregação, atenção às rotas e comunicação segura entre pedestres e operadores."),
  question(27, "Segurança", "safety", "Difícil", "Qual é a melhor resposta a um desvio recorrente no processo?", ["Aceitar como parte da rotina", "Corrigir apenas quando houver auditoria", "Investigar causas, fortalecer controles e acompanhar a eficácia", "Trocar a pessoa responsável"], 2, "Desvios recorrentes pedem análise de causa e melhoria do sistema, não apenas correção pontual."),
  question(28, "Segurança", "safety", "Difícil", "Em um trabalho a quente, o controle essencial inclui:", ["Permissão aplicável, remoção de combustíveis e controle contra incêndio", "Somente abrir uma janela", "Acelerar a tarefa", "Trabalhar sem comunicar para não interromper"], 0, "Trabalhos a quente exigem avaliação, permissão, controle de fontes combustíveis e prontidão para emergência."),
  question(29, "Segurança", "safety", "Difícil", "Por que controles administrativos não devem ser a única barreira quando há risco grave?", ["Porque são sempre mais caros", "Porque dependem do comportamento e podem falhar sozinhos", "Porque não precisam ser documentados", "Porque substituem proteções físicas"], 1, "A hierarquia de controles prioriza eliminar, substituir e proteger antes de depender apenas de instruções."),
  question(30, "Segurança", "safety", "Difícil", "Uma análise de risco deve ser revisada quando:", ["Apenas no fim do ano", "Somente depois de um acidente", "Quando houver mudança de equipamento, material, método ou condição", "Nunca, se já foi assinada"], 2, "Mudanças podem introduzir novos perigos; a análise deve acompanhar a realidade da tarefa."),
  question(31, "Segurança", "safety", "Difícil", "Qual atitude demonstra autoridade para parar o trabalho?", ["Interromper com respeito, explicar o risco e buscar avaliação antes de continuar", "Parar apenas quando alguém da liderança pedir", "Esconder a preocupação para não atrasar", "Continuar e registrar depois"], 0, "Qualquer pessoa deve poder interromper uma condição insegura e pedir ajuda sem medo de retaliação."),
  question(32, "Segurança", "safety", "Difícil", "Quando um incidente acontece, a prioridade inicial é:", ["Definir culpados", "Preservar a produção", "Comunicar apenas no fim do turno", "Cuidar das pessoas, controlar o perigo e acionar a resposta adequada"], 3, "A resposta inicial deve proteger pessoas, controlar a fonte do perigo e iniciar a comunicação prevista."),
  question(33, "Meio ambiente", "environment", "Fácil", "Qual prática reduz o desperdício de água na fábrica?", ["Deixar a torneira aberta durante a limpeza", "Comunicar vazamentos e usar somente o volume necessário", "Lavar áreas sem planejamento", "Aumentar a pressão sempre"], 1, "Usar água de forma consciente e corrigir vazamentos reduz consumo e impactos ambientais."),
  question(34, "Meio ambiente", "environment", "Fácil", "Resíduos devem ser descartados:", ["No recipiente identificado e compatível com sua classificação", "No primeiro recipiente disponível", "Junto com ferramentas", "No ralo quando forem líquidos"], 0, "A segregação correta evita contaminação, exposição e destinação inadequada."),
  question(35, "Meio ambiente", "environment", "Médio", "Ao encontrar um recipiente sem identificação, você deve:", ["Misturar com outro para liberar espaço", "Abrir para verificar o conteúdo", "Isolar e acionar a área responsável pela identificação", "Descartar como resíduo comum"], 2, "Um recipiente desconhecido deve ser tratado como potencialmente perigoso até ser identificado por pessoa competente."),
  question(36, "Meio ambiente", "environment", "Médio", "Qual ação ajuda a prevenir contaminação do solo?", ["Armazenar produtos sobre contenção adequada e inspecionar recipientes", "Deixar tambores diretamente no piso", "Lavar pequenos vazamentos para o ralo", "Guardar materiais ao ar livre sem proteção"], 0, "Contenção e inspeção reduzem a chance de vazamentos alcançarem o solo ou a drenagem."),
  question(37, "Meio ambiente", "environment", "Médio", "O que fazer ao identificar um odor químico incomum?", ["Ignorar se não houver fumaça", "Investigar aproximando o rosto", "Abrir todos os recipientes", "Afastar-se, comunicar e seguir o procedimento de emergência"], 3, "Odor incomum pode indicar exposição; afaste-se e comunique sem tentar investigar de forma insegura."),
  question(38, "Meio ambiente", "environment", "Difícil", "Uma boa prática para reduzir emissões e consumo de energia é:", ["Manter equipamentos ligados sem necessidade", "Identificar perdas, desligar o que não está em uso e melhorar eficiência", "Remover sensores", "Aumentar o tempo de funcionamento"], 1, "Eficiência depende de eliminar perdas e operar recursos conforme a necessidade real."),
  question(39, "Meio ambiente", "environment", "Difícil", "Quando há derramamento de produto, a resposta deve considerar:", ["Somente limpar rapidamente", "Apenas registrar a quantidade", "Segurança das pessoas, contenção, comunicação e destinação correta", "Esconder o local até a manutenção"], 2, "A resposta precisa proteger pessoas, impedir a propagação e garantir tratamento adequado do resíduo."),
  question(40, "Meio ambiente", "environment", "Difícil", "Qual decisão integra segurança, qualidade e meio ambiente?", ["Escolher o caminho mais rápido sempre", "Avaliar riscos, requisitos, consumo e impacto antes de executar", "Transferir o problema para outra área", "Priorizar custo sem avaliar consequências"], 1, "Decisões responsáveis equilibram pessoas, processo, conformidade, qualidade e impacto ambiental."),
'''
text = text[:insert_at] + questions + text[insert_at:]
path.write_text(text)
