from pathlib import Path

path = Path('/home/ubuntu/cummins-sipatma-challenge/client/src/App.tsx')
text = path.read_text()
text = text.replace('type Category = "Segurança" | "Meio ambiente" | "Lean Manufacturing" | "5S" | "Kaizen" | "Kanban";', 'type Category = "Segurança" | "Meio ambiente";')
text = text.replace('type ChallengeKey = "quiz" | "errors" | "lean" | "fiveS" | "kaizen" | "kanban" | "safety" | "environment";', 'type ChallengeKey = "safety" | "environment" | "errors" | "organize";')
text = text.replace('  { id: "lean", icon: "▦", name: "Mestre Lean", detail: "Completou desafios Lean", color: "yellow" },\n', '')
text = text.replace('  { id: "fiveS", icon: "5S", name: "Especialista 5S", detail: "Acertou todos os desafios de 5S", color: "cyan" },\n', '')
start_cards = text.index('const challengeCards:')
end_cards = text.index('\n];', start_cards) + 3
cards = '''const challengeCards: Array<{\n  key: ChallengeKey;\n  title: string;\n  eyebrow: string;\n  description: string;\n  icon: typeof ShieldCheck;\n  tone: string;\n  stat: string;\n}> = [\n  { key: "safety", title: "Quiz de Segurança", eyebrow: "Cuidado com as pessoas", description: "Escolha atitudes seguras para voltar bem para casa e cuidar de quem trabalha com você.", icon: ShieldCheck, tone: "cyan", stat: "15 perguntas" },\n  { key: "environment", title: "Cuide do ambiente", eyebrow: "Cuidado com o entorno", description: "Decida como reduzir impactos, evitar desperdícios e proteger o ambiente da fábrica.", icon: Leaf, tone: "green", stat: "15 perguntas" },\n  { key: "errors", title: "Ache o erro", eyebrow: "Olhar de cuidado", description: "Observe a cena, encontre riscos reais e interrompa situações que podem machucar.", icon: Search, tone: "yellow", stat: "6 riscos reais" },\n  { key: "organize", title: "Organize e cuide", eyebrow: "Cuidado no posto", description: "Organize materiais, mantenha passagens livres e deixe o posto pronto para o próximo colega.", icon: Grid3X3, tone: "green", stat: "3 cuidados" },\n];'''
text = text[:start_cards] + cards + text[end_cards:]
start_bank = text.index('const questionBank: Question[] = [')
end_bank = text.index('\n];', start_bank) + 3
qs = '''const questionBank: Question[] = [
  question(1, "Segurança", "safety", "Fácil", "Verdadeiro ou falso: se eu percebo um risco, devo comunicar mesmo que ninguém tenha se machucado.", ["Verdadeiro", "Falso"], 0, "Comunicar um risco é uma atitude de cuidado que pode evitar uma lesão."),
  question(2, "Segurança", "safety", "Fácil", "Antes de começar uma tarefa diferente, o que demonstra cuidado?", ["Começar logo para ganhar tempo", "Entender os riscos e os controles necessários", "Copiar o colega sem perguntar", "Usar a primeira ferramenta disponível"], 1, "Preparar a tarefa reduz improvisos e exposição desnecessária."),
  question(3, "Segurança", "safety", "Fácil", "Ao encontrar o piso molhado em uma passagem, você deve:", ["Passar depressa", "Avisar somente no fim do turno", "Sinalizar, evitar a área e comunicar", "Cobrir com uma caixa"], 2, "Sinalizar e comunicar protege quem vem depois."),
  question(4, "Segurança", "safety", "Fácil", "Verdadeiro ou falso: uma conversa respeitosa sobre segurança pode evitar que um colega se machuque.", ["Verdadeiro", "Falso"], 0, "Alertar com respeito é uma forma prática de cuidar."),
  question(5, "Segurança", "safety", "Médio", "Ao perceber que uma proteção de máquina foi removida, qual escolha é mais segura?", ["Continuar se a máquina estiver lenta", "Parar e comunicar conforme o procedimento", "Colocar fita e seguir", "Pedir para alguém observar"], 1, "Proteções não devem ser improvisadas ou ignoradas."),
  question(6, "Segurança", "safety", "Médio", "O EPI deve ser entendido como:", ["A única medida necessária", "Uma barreira que complementa os controles do trabalho", "Um item apenas para visitantes", "Uma substituição do treinamento"], 1, "O EPI ajuda, mas não substitui controles coletivos e procedimentos."),
  question(7, "Segurança", "safety", "Médio", "Verdadeiro ou falso: quase-acidentes devem ser registrados porque ajudam a prevenir acidentes.", ["Verdadeiro", "Falso"], 0, "Um quase-acidente mostra onde uma barreira pode ser fortalecida."),
  question(8, "Segurança", "safety", "Médio", "Ao ouvir um alarme, a atitude correta é:", ["Filmar a situação", "Voltar para buscar objetos", "Seguir a rota e a orientação da emergência", "Correr para qualquer saída"], 2, "Seguir o plano mantém a evacuação organizada e segura."),
  question(9, "Segurança", "safety", "Médio", "Se o procedimento não cobre a situação encontrada, você deve:", ["Improvisar pela experiência", "Parar e buscar orientação responsável", "Copiar outra pessoa", "Continuar para não atrasar"], 1, "Quando a condição muda, parar e pedir ajuda é cuidado, não perda de tempo."),
  question(10, "Segurança", "safety", "Difícil", "Antes de intervir em uma máquina, a equipe deve confirmar:", ["Somente o botão desligado", "Isolamento das energias e ausência de energia residual", "Que a produção terminou", "Que há alguém olhando"], 1, "Desligar no painel sozinho não garante ausência de energia perigosa."),
  question(11, "Segurança", "safety", "Difícil", "Verdadeiro ou falso: qualquer pessoa pode interromper uma atividade quando identifica uma condição insegura.", ["Verdadeiro", "Falso"], 0, "Parar uma condição insegura é uma atitude de responsabilidade e cuidado."),
  question(12, "Segurança", "safety", "Difícil", "Em um derramamento, a primeira prioridade é:", ["Esconder o local", "Proteger pessoas, controlar o risco e comunicar", "Lavar rapidamente para o ralo", "Esperar a manutenção"], 1, "A resposta precisa proteger pessoas e impedir que o perigo se espalhe."),
  question(13, "Segurança", "safety", "Difícil", "Uma ferramenta danificada deve ser:", ["Usada com mais cuidado", "Guardada sem avisar", "Retirada de uso, identificada e comunicada", "Compartilhada com outra equipe"], 2, "Retirar a ferramenta evita que outra pessoa seja exposta ao mesmo risco."),
  question(14, "Segurança", "safety", "Difícil", "Qual atitude cuida do próximo turno?", ["Deixar o desvio para quem chegar", "Registrar a condição e deixar o posto seguro", "Esconder materiais", "Desligar a sinalização"], 1, "Cuidado também é entregar um posto seguro e informação clara."),
  question(15, "Segurança", "safety", "Difícil", "Verdadeiro ou falso: cumprir a meta justifica aceitar um atalho que expõe alguém ao risco.", ["Verdadeiro", "Falso"], 1, "Nenhuma meta justifica colocar pessoas em perigo."),
  question(16, "Meio ambiente", "environment", "Fácil", "Verdadeiro ou falso: separar resíduos no local correto é uma atitude de cuidado.", ["Verdadeiro", "Falso"], 0, "A separação correta evita contaminação e facilita o destino adequado."),
  question(17, "Meio ambiente", "environment", "Fácil", "Ao perceber um vazamento de água ou óleo, você deve:", ["Ignorar se for pequeno", "Sinalizar, comunicar e seguir o procedimento", "Lavar para esconder", "Esperar o fim do turno"], 1, "A comunicação rápida ajuda a conter o impacto."),
  question(18, "Meio ambiente", "environment", "Fácil", "Qual atitude reduz desperdício de água?", ["Usar volume necessário e comunicar vazamentos", "Aumentar a pressão sempre", "Deixar a torneira aberta", "Lavar sem planejar"], 0, "Usar apenas o necessário é cuidado com um recurso de todos."),
  question(19, "Meio ambiente", "environment", "Fácil", "Um recipiente sem identificação deve ser:", ["Aberto para descobrir", "Misturado com outro", "Isolado e encaminhado para identificação", "Descartado no lixo comum"], 2, "Material desconhecido deve ser tratado com cautela."),
  question(20, "Meio ambiente", "environment", "Fácil", "Verdadeiro ou falso: jogar um líquido no ralo é aceitável se ele parecer inofensivo.", ["Verdadeiro", "Falso"], 1, "A aparência não define a destinação; siga a identificação e o procedimento."),
  question(21, "Meio ambiente", "environment", "Médio", "Como reduzir a chance de um produto atingir o solo?", ["Armazenar sobre contenção e inspecionar recipientes", "Deixar tambores direto no piso", "Lavar pequenos vazamentos", "Guardar ao ar livre"], 0, "Contenção e inspeção evitam impactos maiores."),
  question(22, "Meio ambiente", "environment", "Médio", "Qual escolha evita desperdício de material?", ["Pedir sempre material extra", "Planejar o uso e comunicar perdas", "Misturar sobras com produto bom", "Esconder o material danificado"], 1, "Planejar e comunicar permitem corrigir a origem da perda."),
  question(23, "Meio ambiente", "environment", "Médio", "Ao identificar odor químico incomum, você deve:", ["Investigar aproximando o rosto", "Ignorar se não houver fumaça", "Afastar-se, comunicar e seguir a emergência", "Abrir recipientes"], 2, "Não se exponha para investigar; afaste-se e comunique."),
  question(24, "Meio ambiente", "environment", "Médio", "Verdadeiro ou falso: reduzir desperdício também ajuda a tornar o posto mais seguro.", ["Verdadeiro", "Falso"], 0, "Menos excesso libera espaço e reduz improvisos e riscos."),
  question(25, "Meio ambiente", "environment", "Médio", "Qual prática ajuda a economizar energia sem criar risco?", ["Desligar qualquer equipamento sem avaliar", "Identificar perdas e desligar somente o que não é necessário", "Remover sensores", "Manter tudo ligado"], 1, "Economia deve respeitar procedimento e segurança do processo."),
  question(26, "Meio ambiente", "environment", "Difícil", "Em um derramamento, a resposta deve incluir:", ["Somente limpeza rápida", "Contenção, comunicação, proteção das pessoas e destinação correta", "Esconder o local", "Jogar água"], 1, "Cuidar do ambiente começa protegendo pessoas e impedindo a propagação."),
  question(27, "Meio ambiente", "environment", "Difícil", "Verdadeiro ou falso: um impacto ambiental pequeno não precisa ser comunicado.", ["Verdadeiro", "Falso"], 1, "Pequenos desvios podem se repetir e se tornar impactos maiores."),
  question(28, "Meio ambiente", "environment", "Difícil", "Qual decisão considera cuidado com pessoas e ambiente?", ["Escolher apenas pelo custo", "Avaliar riscos, consumo, resíduos e consequências", "Transferir o problema", "Produzir mais para compensar"], 1, "Cuidado exige olhar para as consequências da decisão."),
  question(29, "Meio ambiente", "environment", "Difícil", "Ao encontrar resíduo misturado, a atitude correta é:", ["Deixar como está", "Separar sem avaliar o risco", "Sinalizar e pedir orientação para corrigir com segurança", "Colocar tudo em outro recipiente"], 2, "A correção deve evitar exposição e seguir a classificação adequada."),
  question(30, "Meio ambiente", "environment", "Difícil", "Verdadeiro ou falso: cuidar do ambiente é responsabilidade de todas as pessoas da fábrica.", ["Verdadeiro", "Falso"], 0, "Cada atitude diária contribui para um ambiente mais protegido."),
];'''
text = text[:start_bank] + qs + text[end_bank:]
text = text.replace('questionBank.length}', 'questionBank.length}')
text = text.replace('startChallenge("quiz")', 'startChallenge("safety")')
text = text.replace('activeChallenge === "kanban"', 'activeChallenge === "organize"')
text = text.replace('challenge === "kanban"', 'challenge === "organize"')
text = text.replace('activeChallenge !== "kanban"', 'activeChallenge !== "organize"')
text = text.replace('key: "quiz"', 'key: "safety"')
text = text.replace('"Quiz de Segurança"', '"Quiz de Segurança"')
text = text.replace('challenge === "quiz"', 'challenge === "safety"')
text = text.replace('const category = challenge === "safety" ? "Segurança" : "Meio ambiente";', 'const category = challenge === "safety" ? "Segurança" : "Meio ambiente";')
text = text.replace('...(activeChallenge === "lean" ? ["lean"] : []), ...(activeChallenge === "fiveS" && correct === total ? ["fiveS"] : []), ', '')
text = text.replace('activeChallenge === "errors" ? <ErrorHunt', 'activeChallenge === "errors" ? <ErrorHunt')
text = text.replace('activeChallenge === "organize" ? `${kanbanCards.done.length}/3`', 'activeChallenge === "organize" ? `${kanbanCards.done.length}/3`')
text = text.replace('activeChallenge === "errors" ? <ErrorHunt foundErrors={foundErrors} wrongErrorClicks={wrongErrorClicks} chooseError={chooseError} missError={missError} /> : activeChallenge === "organize" ? <KanbanBoard', 'activeChallenge === "errors" ? <ErrorHunt foundErrors={foundErrors} wrongErrorClicks={wrongErrorClicks} chooseError={chooseError} missError={missError} /> : activeChallenge === "organize" ? <KanbanBoard')
text = text.replace('MISSÃO KANBAN', 'MISSÃO ORGANIZE E CUIDE').replace('Libere o fluxo sem sobrecarregar o sistema.', 'Deixe o posto pronto para cuidar de quem vem depois.').replace('Selecione um cartão e escolha o próximo estágio. Respeite o limite de trabalho em processo.', 'Selecione um cuidado e organize cada item no lugar certo.').replace('WIP', 'CUIDADOS').replace('Em produção', 'Em cuidado').replace('Limite WIP: 2 cartões', 'Até 2 itens em cuidado').replace('Puxar quando houver capacidade', 'Itens que precisam de atenção').replace('Entregue ao próximo processo', 'Posto pronto e seguro')
text = text.replace('O 5S facilita encontrar e devolver ferramentas.', 'Organização facilita encontrar e devolver ferramentas.')
text = text.replace('Você encontra e elimina desperdícios para liberar o fluxo.', 'Você identifica um cuidado e deixa o posto mais seguro.').replace('Você organiza o posto e torna as anormalidades visíveis.', 'Você organiza o posto para proteger o próximo colega.').replace('Você escolhe uma contramedida simples e sustentável.', 'Você escolhe uma atitude de cuidado.').replace('Você transforma conhecimento em uma decisão de processo.', 'Você transforma conhecimento em uma atitude segura.')
path.write_text(text)
