from pathlib import Path

path = Path('/home/ubuntu/cummins-sipatma-challenge/client/src/App.tsx')
text = path.read_text()
anchor = '\n];\n\nconst sectorOptions = ['
pos = text.index(anchor)
questions = r'''
  question(41, "Meio ambiente", "environment", "Fácil", "Qual é o primeiro passo ao identificar uma perda de material?", ["Acelerar o consumo para acabar logo", "Comunicar e investigar a origem da perda", "Esconder o material danificado", "Misturar com produto bom"], 1, "Comunicar a perda permite conter o impacto e investigar a causa antes que ela se repita."),
  question(42, "Meio ambiente", "environment", "Fácil", "O que deve ser feito com uma lâmpada quebrada?", ["Colocar no lixo comum sem proteção", "Esmagar os pedaços para caber", "Isolar e descartar conforme o procedimento aplicável", "Lavar no ralo"], 2, "Lâmpadas podem conter materiais que exigem manuseio e destinação específicos."),
  question(43, "Meio ambiente", "environment", "Médio", "Como evitar que um produto alcance a drenagem em um vazamento?", ["Usar contenção adequada e proteger ralos conforme o plano", "Empurrar o líquido com água", "Abrir mais ralos", "Aguardar a evaporação"], 0, "A contenção na fonte e a proteção da drenagem limitam a propagação do produto."),
  question(44, "Meio ambiente", "environment", "Médio", "A compra de um insumo mais barato deve considerar:", ["Somente o preço unitário", "Apenas o prazo de entrega", "Consumo, segurança, resíduos e ciclo de vida", "Se a embalagem é maior"], 2, "Decisões sustentáveis consideram impactos além do custo imediato."),
  question(45, "Meio ambiente", "environment", "Médio", "Qual comportamento reduz a geração de resíduos de embalagem?", ["Pedir material extra para garantir", "Escolher embalagens adequadas e evitar descartáveis desnecessários", "Descartar sobras junto com recicláveis", "Abrir todas as embalagens antes de usar"], 1, "Planejamento e escolha adequada de materiais reduzem resíduos na origem."),
  question(46, "Meio ambiente", "environment", "Difícil", "Um indicador ambiental piorou por três meses. A equipe deve:", ["Parar de medir", "Alterar a meta para parecer melhor", "Analisar tendência, causas e ações corretivas", "Registrar somente o melhor mês"], 2, "Indicadores servem para revelar tendências e orientar ações verificáveis."),
  question(47, "Meio ambiente", "environment", "Difícil", "Qual é uma evidência de controle ambiental eficaz?", ["Um procedimento guardado sem uso", "Uma inspeção com ação concluída e resultado acompanhado", "Uma promessa verbal", "Uma área sem placa"], 1, "Controle eficaz combina ação, responsabilidade, evidência e verificação do resultado."),
  question(48, "Meio ambiente", "environment", "Difícil", "Ao observar fumaça ou emissão fora do padrão, a atitude correta é:", ["Ignorar se o turno estiver acabando", "Filmar e publicar imediatamente", "Afastar-se se houver risco e comunicar pelo canal definido", "Cobrir a saída da emissão"], 2, "Emissões anormais devem ser comunicadas com segurança para avaliação e resposta adequadas."),
  question(49, "5S", "fiveS", "Fácil", "No 5S, separar o necessário do desnecessário significa:", ["Guardar tudo para evitar falta", "Manter apenas o que tem uso definido no local", "Jogar fora sem consultar", "Colocar itens em qualquer armário"], 1, "O senso de utilização reduz excesso e deixa disponível apenas o que faz sentido para a atividade."),
  question(50, "5S", "fiveS", "Fácil", "Qual é um exemplo de Seiton?", ["Definir lugar, identificação e acesso para cada item", "Limpar somente antes da auditoria", "Comprar mais ferramentas", "Retirar todas as etiquetas"], 0, "Ordenar é definir um lugar visível e funcional para cada coisa."),
  question(51, "5S", "fiveS", "Fácil", "A limpeza no 5S também serve para:", ["Deixar a área bonita para visitantes", "Encontrar fontes de sujeira, vazamentos e anormalidades", "Substituir manutenção", "Evitar inspeções"], 1, "Limpar permite inspecionar e perceber anormalidades antes que se agravem."),
  question(52, "5S", "fiveS", "Fácil", "Uma etiqueta vermelha deve ser usada para:", ["Identificar itens sem uso claro para avaliação", "Marcar itens favoritos", "Decorar a bancada", "Indicar que a tarefa acabou"], 0, "A etiqueta vermelha ajuda a separar dúvidas e excessos para decisão responsável."),
  question(53, "5S", "fiveS", "Médio", "Uma bancada com ferramentas misturadas aumenta o risco de:", ["Encontrar tudo mais rápido", "Perda de tempo, danos e uso de ferramenta inadequada", "Melhorar o fluxo", "Reduzir o estoque"], 1, "A desorganização dificulta localizar, conferir e devolver ferramentas corretamente."),
  question(54, "5S", "fiveS", "Médio", "Qual é a melhor forma de manter um padrão 5S?", ["Depender da memória de cada pessoa", "Usar referências visuais, rotina e responsáveis definidos", "Fazer uma grande limpeza anual", "Mudar o local toda semana"], 1, "Padrões visuais e rotina tornam o comportamento esperado claro e sustentável."),
  question(55, "5S", "fiveS", "Médio", "Se um item não tem local definido, a equipe deve:", ["Deixá-lo no chão até alguém procurar", "Criar uma solução visual e confirmar com o processo", "Esconder na gaveta mais próxima", "Comprar outro igual"], 1, "O local precisa ser definido de forma funcional para evitar repetição da desordem."),
  question(56, "5S", "fiveS", "Médio", "Qual atitude é contrária ao senso de limpeza?", ["Investigar uma fonte de vazamento", "Limpar e devolver o material ao lugar", "Usar pano sujo para espalhar óleo e ocultar a origem", "Manter o piso sinalizado durante a limpeza"], 2, "Limpeza não deve esconder a causa; deve revelar e tratar a anormalidade."),
  question(57, "5S", "fiveS", "Médio", "Uma área visualmente organizada, mas com rotas bloqueadas:", ["Está adequada porque parece limpa", "Ainda possui um risco e precisa de correção", "Só precisa de uma foto", "Deve receber mais materiais"], 1, "Organização precisa apoiar segurança e fluxo, não apenas aparência."),
  question(58, "5S", "fiveS", "Médio", "Quem é responsável por manter o 5S?", ["Somente a equipe de limpeza", "Somente a liderança", "Todas as pessoas que usam e cuidam do local", "A auditoria externa"], 2, "5S é uma prática diária compartilhada por quem atua no processo."),
  question(59, "5S", "fiveS", "Difícil", "Um padrão visual deve ser revisado quando:", ["Nunca, depois de publicado", "O processo muda ou o padrão deixa de evitar desvios", "Somente quando alguém reclamar", "Apenas durante a auditoria"], 1, "Padrões precisam acompanhar mudanças e demonstrar que continuam eficazes."),
  question(60, "5S", "fiveS", "Difícil", "Qual indicador mostra uma oportunidade de melhoria no 5S?", ["Itens sem localização ou devolvidos em locais diferentes", "Todos os armários identificados", "Rotas livres", "Ferramentas em sombra definida"], 0, "Itens fora do padrão mostram que o sistema precisa ser ajustado ou reforçado."),
  question(61, "5S", "fiveS", "Difícil", "Ao encontrar um equipamento sem identificação, você deve:", ["Assumir que está liberado", "Identificar de qualquer forma", "Segregar e solicitar identificação conforme o procedimento", "Usar e depois perguntar"], 2, "Identificação evita uso indevido e permite controlar status e responsabilidade."),
  question(62, "5S", "fiveS", "Difícil", "Uma boa auditoria 5S deve:", ["Procurar culpados", "Comparar evidências com o padrão e gerar ações úteis", "Avaliar somente a aparência", "Ser feita sem falar com usuários"], 1, "Auditoria deve aprender com o processo e gerar melhorias verificáveis."),
  question(63, "5S", "fiveS", "Fácil", "Por que demarcar áreas de circulação?", ["Para ocupar mais espaço", "Para deixar claro onde pessoas e materiais podem circular", "Para substituir treinamento", "Para esconder obstáculos"], 1, "Demarcações tornam o fluxo esperado visível e ajudam a prevenir conflitos e bloqueios."),
  question(64, "5S", "fiveS", "Médio", "Quando um armário está cheio de itens raramente usados, o melhor é:", ["Adicionar outro sem avaliar", "Revisar uso, necessidade e destino dos itens", "Misturar com itens de emergência", "Retirar as etiquetas"], 1, "Revisar a necessidade evita excesso e libera espaço para o que realmente é usado."),
  question(65, "5S", "fiveS", "Médio", "Qual solução facilita a devolução de uma ferramenta?", ["Um local sem identificação", "Uma sombra ou endereço visual próximo ao ponto de uso", "Uma caixa trancada sem responsável", "Um armário distante"], 1, "A melhor solução combina identificação e proximidade com o trabalho."),
  question(66, "5S", "fiveS", "Difícil", "Se a mesma anormalidade aparece em várias auditorias, é necessário:", ["Parar de registrar", "Tratar a causa e revisar o padrão ou a rotina", "Reduzir a nota", "Trocar o formulário"], 1, "Repetição indica que a ação anterior não foi suficiente ou não foi sustentada."),
  question(67, "5S", "fiveS", "Difícil", "O 5S apoia a segurança porque:", ["Elimina a necessidade de EPI", "Reduz desordem, facilita percepção de desvios e melhora o fluxo", "Substitui bloqueio de energia", "Garante que ninguém erre"], 1, "Um ambiente ordenado ajuda a perceber riscos, mas não substitui controles técnicos e procedimentos."),
  question(68, "5S", "fiveS", "Fácil", "Qual atitude sustenta o senso de autodisciplina?", ["Fazer somente quando alguém observa", "Cumprir o padrão e ajudar a melhorá-lo quando necessário", "Esperar a próxima auditoria", "Deixar para o colega"], 1, "Autodisciplina é praticar o padrão de forma consistente e participar da melhoria."),
  question(69, "5S", "fiveS", "Médio", "Ao propor retirar um item de uma área, é importante:", ["Descartar imediatamente", "Confirmar uso, dono, condição e destino correto", "Esconder em outra área", "Esperar que desapareça"], 1, "A decisão evita descarte indevido e transfere o problema para o local correto."),
  question(70, "5S", "fiveS", "Difícil", "Qual resultado indica um 5S maduro?", ["A área fica perfeita apenas no dia da auditoria", "As pessoas identificam desvios e corrigem o padrão no cotidiano", "Não existem registros de problemas", "Tudo depende de uma pessoa"], 1, "Maturidade aparece quando o cuidado está incorporado à rotina e gera aprendizado contínuo."),
'''
text = text[:pos] + '\n' + questions + text[pos:]
text = text.replace('stat: "Missão 5S"', 'stat: "20 perguntas"', 1)
path.write_text(text)
